### ISSUE TITLE
qt4 support issue (btw, thank you a lot for your GREAT JOB!)

### ISSUE THREAD

**Issue by anyonepaw** [Gabrielcarvfer/NS3#4]
Hello, Gabriel! I (and other students) so happy to find your project! You save our souls by adding CMakeLists.txt to NS3!!!
My issue is: I have Qt5, but it requires Qt4 - (I work on mac os, mb it does the problem, but..)
In one repo that I found was:

> https://github.com/cartr/homebrew-qt4

> Please note: Qt4 is unsupported by its creators, so there are likely security/usability problems with it that will never be resolved. If you can, please consider migrating your projects to Qt5.

when I add qt4(from repo below) to my project (mb sooner I will fix it, I don't know)
```
VcPkg already bootstrapped 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.13/Modules/FindQt4.cmake:1313 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  3rd-party/netanim/CMakeLists.txt:157 (find_package)
```

when I change qt4 to qt5 it reports:
```
VcPkg already bootstrapped
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.13/Modules/FindQt4.cmake:1313 (message):
  Found unsuitable Qt version "5.12.0" from /usr/local/opt/qt/bin/qmake, this
  code requires Qt 4.x
Call Stack (most recent call first):
  3rd-party/netanim/CMakeLists.txt:157 (find_package)
```

(I see I have a problem with VcPkg too, my bad)

So, is it possible to migrate to qt5 or to fix this for us?

**Comment by Gabrielcarvfer** [comment]
Hello. I felt the same after debugging the simulations with CLion. x)
Yup, there's no cmake support for Qt5 yet. I will try fixing it and, if it works, I will push it later today.
BTW, I'm not testing anything on Mac OS, so you might hit other problems.

The Vcpkg messages are mostly to alert about issues. You can disable them or remove the WARNING flag if they bother you.

**Comment by Gabrielcarvfer** [comment]
@anyonepaw, please test the updated version. For the time being, select the Qt version in the main CMakeLists.

**Comment by anyonepaw** [comment]
@Gabrielcarvfer wooow, thank you, that's superb!!! 👍 

**now, QT is working for me!**
`set(USE_QT 5)# Choose between Qt 4 or 5` 

mb someone need my experience on mac os:

**Vcpkg fix:**
can be installed on mac os by `brew install pkgconfig` 

**LibRT fix:**
in CMakeLists.txt:
```
option(NS3_LIBRT "Build with RT support" OFF)
set(NS3_LIBRT OFF) #not working on Windows  -- and on mac to;)
```

**"./waf --permission denied" fix:**
`chmod 755 waf`

**it works perfectly! 🥇 THANK YOU!**

<img width="1241" alt="screenshot 2019-02-17 at 17 13 13" src="https://user-images.githubusercontent.com/32063879/52914282-8d361500-32d7-11e9-93e1-c8ae0972d4c2.png">

with waf I still have problems (mac os, ugh), but I think, that it won't bother me in the future ('cause I use NetAnim now). If I fix it I will report!:)
**int64x64_t and operator bug**
<img width="1226" alt="screenshot 2019-02-17 at 17 18 58" src="https://user-images.githubusercontent.com/32063879/52914334-18afa600-32d8-11e9-8c32-6d135a3fc9e8.png">

**Comment by Gabrielcarvfer** [comment]
@anyonepaw , waf probably won't work since I've changed other stuff. The int64x64 error can probably be fixed setting to use the "double" option on macros_and_definitions.

**Comment by anyonepaw** [comment]
@Gabrielcarvfer 

> setting to use the "double" option on macros_and_definitions

 I find something like this in macros_and_definitions, but what should I do to use it?
```
    #Process core-config
    set(INT64X64 "128")

	if (${CMAKE_CXX_COMPILER_ID} EQUAL MSVC)
		message(WARNING "Microsoft MSVC doesn't support 128-bit integer operations. Falling back to double.")
		set(INT64X64 "DOUBLE")
	endif()

    if(INT64X64 STREQUAL "128")
        add_definitions(-DHAVE___UINT128_T)
        add_definitions(-DINT64X64_USE_128)
    elseif(INT64X64 STREQUAL "DOUBLE")
        add_definitions(-DINT64X64_USE_DOUBLE)
    elseif(INT64X64 STREQUAL "CAIRO")
        add_definitions(-DINT64X64_USE_CAIRO)
    else()
    endif()
```
and
NetAnim is not working yet?^^' Sorry that you have to bear with me>_<
<img width="1240" alt="screenshot 2019-02-17 at 18 57 08" src="https://user-images.githubusercontent.com/32063879/52915495-cecdbc80-32e5-11e9-8301-be566a0ef658.png">

**Comment by Gabrielcarvfer** [comment]
Change to set(INT64X64 "DOUBLE") . I will add a new check for the Mac just like the MSVC one.
You're using CLion, first select the netanim build target, then click to run. If you already compiled it and prefer to launch from the terminal, navigate to NS3/build/bin and netanim binary will be there.

**Comment by anyonepaw** [comment]
Hello, Gabriel! hm, I renew project with your last fix, but, seems, my mac feels the same. It's strange, I see, that it is working on CMake stage
```
 if(APPLE)
            message(WARNING "Apples CLang doesn't support 128-bit integer operations. Falling back to double.")
            set(INT64X64 "DOUBLE")
        endif()
```
<img width="1241" alt="screenshot 2019-02-18 at 07 01 02" src="https://user-images.githubusercontent.com/32063879/52927332-028efd80-334b-11e9-934c-2427603d802f.png">

```
./waf configure
./waf
```

<img width="1227" alt="screenshot 2019-02-18 at 06 39 33" src="https://user-images.githubusercontent.com/32063879/52926707-fd7c7f00-3347-11e9-829d-91912d804132.png">

And thank you!:) Netanim works! 👍
