### ISSUE TITLE
How to link another libs to your project

### ISSUE THREAD

**Issue by anyonepaw** [Gabrielcarvfer/NS3#5]
@Gabrielcarvfer, hello!
It's me again:\ 
I new to such big projects on c++ and it is difficult for me to add libraries.  
I try to link to .a libs commonly (and .dylib), but I have already tried all variants to link them, spent several days, so I awfully need your help:C

for example,
[I followed this tutorial on youtube for link .a lib](https://www.youtube.com/watch?v=CqjokCekMM8&t=977s&list=LLxmkDVgItHJPViu9_iQeGmQ&index=22)

and cought these:
 
<img width="904" alt="screenshot 2019-03-08 at 00 04 23" src="https://user-images.githubusercontent.com/32063879/53988898-a3e0c680-4135-11e9-9b1f-d1e4b841c890.png">

This is my FindKeccak:

<img width="981" alt="screenshot 2019-03-08 at 00 14 35" src="https://user-images.githubusercontent.com/32063879/53989460-14d4ae00-4137-11e9-9336-0e3d3fca5f30.png">

With .dylib I have this:
 
<img width="1057" alt="screenshot 2019-03-07 at 23 49 48" src="https://user-images.githubusercontent.com/32063879/53988062-a9d5a800-4133-11e9-935a-c3b542e487f8.png">

<img width="890" alt="screenshot 2019-03-07 at 21 59 13" src="https://user-images.githubusercontent.com/32063879/53988455-89f2b400-4134-11e9-9ad1-bca2b808d5de.png">

If I try to take only these files that I need in my module, 

<img width="407" alt="screenshot 2019-03-07 at 23 55 43" src="https://user-images.githubusercontent.com/32063879/53988416-73e4f380-4134-11e9-9933-addae1caa2fb.png">

but still I failed with it in the end:

<img width="1120" alt="screenshot 2019-03-06 at 21 49 16" src="https://user-images.githubusercontent.com/32063879/53988527-ba3a5280-4134-11e9-9f12-cb21ca9a5fb9.png">

Haha..it is so terrible
I chasing my tail about that one
I really do need your HELP:C Maybe you can give me a piece of advice:(

**Comment by Gabrielcarvfer** [comment]
It happens. BTW, that's exactly why python is my preferred language. :)

Here go a few points based on the images.

First image: CMake didn't find the Keccak library and variables were set not NOTFOUND. Always check if the library was found before trying to link, and after that you need to figure out why the library was not found. You can find examples in the process_options macro inside buildsupport/macros_and_definitions.cmake .

Second image: you seem to point out the keccak folder (FIND_KECCAK_FOLDER) to a keccak folder in the root (/keccak). Based on your project (cwd/NS3/keccak), it should be ./keccak or ${PROJECT_SOURCE_DIR}/keccak. I'm not really sure if you need to change find_path and find_library suffixes after.

Third and fourth images: for whatever reason it's trying to look for a library folder pointing to a library (-l is used to point out a library to link, -L is used to point out a folder containing libraries that can be linked). It shouldn't be using the system libpcre2 and libgsl, as those are built with VcPkg. Those ones are probably my fault.

Not sure about the curl undefined symbols: or the library was not linked or the library was not built for x86. 

Nothing wrong on the fifth image.

Sixth image: duplicated symbols. I'm not sure if you should be linking objects instead of the libraries. Are you sure those .c.o files should be in the lib folder?

**Comment by anyonepaw** [comment]
Hello, @Gabrielcarvfer! I so appreciate your quick and detailed responses:)
It happens. BTW, that's exactly why python is my preferred language. :) -> 
:) 
yep, python is more comfortable in any way!

After your explanations _I realised one my really big mistake_ (I try all your offers also before) - but firstly
I just want to quickly explain what I'm trying to do

_Chapter 1: what I try to do_
I need to take this project _iota.lib.cpp_:
as you can see there are dependencies: keccak, json, curl

<img width="1280" alt="54074112-ba0a9600-429f-11e9-8edd-1b1f7748359a" src="https://user-images.githubusercontent.com/32063879/54074225-fe4a6600-42a0-11e9-86a2-629afda52a4c.png">

And to make it like an NS3-module, as you saw on fifth image:

<img width="1001" alt="Screenshot 2019-03-09 at 19 13 33" src="https://user-images.githubusercontent.com/32063879/54074083-4cf70080-429f-11e9-87b0-df4596f4a491.png">

So, as you can see, I mess sources and headers and write them out in CMakeLists.txt as I saw like you did in modules:  (there you can see my strange attempt to add keccak dependencies by hands:'D)

<img width="1280" alt="Screenshot 2019-03-09 at 19 17 47" src="https://user-images.githubusercontent.com/32063879/54074126-e32b2680-429f-11e9-8150-1d420168f3d3.png">
<img width="1280" alt="Screenshot 2019-03-09 at 19 18 14" src="https://user-images.githubusercontent.com/32063879/54074129-f3db9c80-429f-11e9-987f-bafbe54ad0bc.png">

And I add it like a one of the modules in main CMakeLists.txt:

<img width="1280" alt="Screenshot 2019-03-09 at 19 29 10" src="https://user-images.githubusercontent.com/32063879/54074262-7a44ae00-42a1-11e9-965a-6e8163d5d347.png">


so, all my troubles **are these dependencies (keccak, json, curl)** and I trying to add them like a libraries (>_<) and I can't do nothing because my sources depends on them

It begins when I found these include 
<img width="1280" alt="Screenshot 2019-03-09 at 19 31 11" src="https://user-images.githubusercontent.com/32063879/54074284-ce4f9280-42a1-11e9-9605-6a9b02bf4b97.png">

and all cpp files also need keccak

<img width="834" alt="Screenshot 2019-03-09 at 19 34 40" src="https://user-images.githubusercontent.com/32063879/54074331-4027dc00-42a2-11e9-8fba-77b5d8d88e76.png">


So, I started to find ways to add keccak to this project) Thank you for the reading this sad story with torturing with c++ linking:D So, what I need to do is **to make these dependencies and that include work**

_Chapter 2: what I found_

Look! Developers also included these libs to their project and **left to so pity me all the scripts:**

<img width="1280" alt="Screenshot 2019-03-09 at 19 39 35" src="https://user-images.githubusercontent.com/32063879/54074390-f7245780-42a2-11e9-82e5-96ebfa2c68a4.png">


so, I copy all their CMake files and part of main CMakeLists.txt
and look, it even build me something:

<img width="1025" alt="Screenshot 2019-03-09 at 20 35 48" src="https://user-images.githubusercontent.com/32063879/54075021-dbbd4a80-42aa-11e9-8dfe-1ebe58da05de.png">


BUT

There are problems T_T:

* I haven't target with such name as my project

<img width="696" alt="Screenshot 2019-03-09 at 19 43 33" src="https://user-images.githubusercontent.com/32063879/54074438-8cbfe700-42a3-11e9-90ad-a6c95d2fecb5.png">

* Ok, I done i with scratch simulator as a target, but...

<img width="1280" alt="Screenshot 2019-03-09 at 20 30 06" src="https://user-images.githubusercontent.com/32063879/54074949-fe9b2f00-42a9-11e9-8b08-498b7f54aa11.png">

So, I found this solution, but all the same, what is going on?:'D

**Comment by Gabrielcarvfer** [comment]
> Hello, @Gabrielcarvfer! I so appreciate your quick and detailed responses:)

You're welcome.

> I need to take this project _iota.lib.cpp_: as you can see there are dependencies: keccak, json, curl

This project is a standalone library. You should build it before even trying to link to the NS3 module, or you can include a ExternalProject(iota) on the NS3 module CMakeLists.txt to trigger its build, following the example of the keccak cmakelists on the following image.

> <img alt="Screenshot 2019-03-09 at 20 30 06" width="1280" src="https://user-images.githubusercontent.com/32063879/54074949-fe9b2f00-42a9-11e9-8b08-498b7f54aa11.png">

> So, as you can see, I mess sources and headers and write them out in CMakeLists.txt as I saw like you did in modules: (there you can see my strange attempt to add keccak dependencies by hands:'D)
 
Those modules are supposed to be components for the simulator, not third party libraries. I would say that there's a <5% chance of working, because you might not be respecting how the components are built, skipping all sorts of configurations for the library and its dependencies. 

> And I add it like a one of the modules in main CMakeLists.txt:

You should write a NS3 module with a device/stack/application that use the iota/keccak/json/curl API on its implementation, and then link the required libraries to the NS3 module.

> so, all my troubles **are these dependencies (keccak, json, curl)** and I trying to add them like a libraries (>_<) and I can't do nothing because my sources depends on them.

Slow down and try this:
- Move this Iota folder to 3rd-party libraries folder, or outside of the NS3 directory
- After that, open the Iota folder with CLion and build it
- Check where it put the resulting libraries
- Open the NS3 folder with CLion
- Navigate to src
- Create your module folder
- Create a model folder 
- Code your device/stack/application.
- Rewrite your module CMakeLists.txt with the proper module name a.k.a. set(name mymodule)
- Write the path to your module sources (source_files, header_files)
- Include the iota libraries on the libraries_to_link list (to save up your time, you can hardcode the absolute paths of the iota libraries).

**Comment by anyonepaw** [comment]
Hello!:)

So, after these steps been done,
- Move this Iota folder to 3rd-party libraries folder, or outside of the NS3 directory
- After that, open the Iota folder with CLion and build it
- Check where it put the resulting libraries

I have:

<img width="358" alt="Screenshot 2019-03-10 at 19 12 15" src="https://user-images.githubusercontent.com/32063879/54087832-513b2080-4368-11e9-86db-8ea90a81a083.png">

It creates me only full iota library

After these:

- Navigate to src
- Create your module folder
- Create a model folder
- Code your device/stack/application
- Rewrite your module CMakeLists.txt with the proper module name a.k.a. set(name mymodule)
- Write the path to your module sources (source_files, header_files)
- Include the iota libraries on the libraries_to_link list (to save up your time, you can hardcode the absolute paths of the iota libraries)

so, these is my new module:

<img width="1280" alt="Screenshot 2019-03-10 at 19 47 42" src="https://user-images.githubusercontent.com/32063879/54088261-4fc02700-436d-11e9-9656-427733a92179.png">

I wrote the full path to library, but it still can't find it:\

<img width="1280" alt="Screenshot 2019-03-10 at 19 45 59" src="https://user-images.githubusercontent.com/32063879/54088260-4e8efa00-436d-11e9-92f9-540542cb46f1.png">

😭 



So, and I have another following questions to you 0_0
_(Oh, I so apologise, answer me, only if you have time)_

- as I understood, these variables aren't defined:
<img width="1267" alt="Screenshot 2019-03-10 at 22 10 28" src="https://user-images.githubusercontent.com/32063879/54090060-332dea00-4381-11e9-8db9-8f05fbba5551.png">

and I see, that it has these headers from built/ns3/ folder

<img width="1280" alt="Screenshot 2019-03-10 at 22 12 49" src="https://user-images.githubusercontent.com/32063879/54090085-80aa5700-4381-11e9-933c-77c23023412f.png">

so, when it will find libiota.dylib (I so hope, I believe in me and it^^'), how will be include look like?
I need to write a path then, like #include "../3d-party/iota.lib.cpp/include/attach-to-tangle.h"?

- I need to write a module in NS3 to make this code work with ns3 network modules in scratch.
IOTA is a cryptocurrency, so I hope to write a code to attach its functionality to NS3 node (and addresses and so on), how do you think, is it possible?
I found a project, [which fully integrated with NS3, like a module](https://github.com/arthurgervais/Bitcoin-Simulator/tree/master/src/applications/helper) (so I'm going to write something like this) - it works, it is like an example

<img width="1280" alt="Screenshot 2019-03-10 at 22 23 09" src="https://user-images.githubusercontent.com/32063879/54090226-efd47b00-4382-11e9-90fc-ad9cf33ac07a.png">

but, okay, tests don't work^^' (and I have no idea why (as always)), but maybe never mind about it

 
<img width="1280" alt="Screenshot 2019-03-11 at 00 06 01" src="https://user-images.githubusercontent.com/32063879/54091509-dbe44580-4391-11e9-827e-f39b223d1afd.png">
<img width="1280" alt="Screenshot 2019-03-11 at 00 06 37" src="https://user-images.githubusercontent.com/32063879/54091508-dab31880-4391-11e9-819f-f666666cd788.png">
<img width="1276" alt="Screenshot 2019-03-11 at 00 06 44" src="https://user-images.githubusercontent.com/32063879/54091511-dd157280-4391-11e9-9ec9-36f7590a8a72.png">

**Comment by Gabrielcarvfer** [comment]
@anyonepaw sorry for the late answer, but I really didn't had time to properly answer.

Libiota part: OK.

Tangle-network part: 
- change the hardwired part to libiota (remove path and extension) and use link_directories(${CMAKE_SOURCE_DIR}/3rd-party/iota.lib.cpp/lib) to include the folder that contains the library. If you want to access the libraries, you need to use include_directories(${CMAKE_SOURCE_DIR}/3rd-party/iota.lib.cpp/include). This is not trivial to automate as it can vary wildly depending on the library being used.
- remember that you need to include the "tangle-network" to the libs_to_build in the main CMakeLists.txt (NS3/CMakeLists.txt). If you don't do this, your NS3 modules won't be built.

Bitcoin application part:
- including the "bitcoin" module on the libs_to_build should make it work.

**Comment by anyonepaw** [comment]
@Gabrielcarvfer oh, never mind! It's all right!:)

Tangle-network part: Thank you a lot! Got it!

Bitcoin application part: I have made it working already:) 
including the "bitcoin" module on the libs_to_build should make it work -> yep, I  made it 

<img width="317" alt="Screenshot 2019-04-10 at 14 04 02" src="https://user-images.githubusercontent.com/32063879/55873867-70141900-5b99-11e9-94db-80e3f09d2411.png">

and also
 just link all libs to it's own CmakeLists.txt, so all dependencies works now:

<img width="337" alt="Screenshot 2019-04-10 at 13 55 30" src="https://user-images.githubusercontent.com/32063879/55873566-a8ffbe00-5b98-11e9-801d-ef20962d45f2.png">

Thank you for your help!:) I try all for tangle and report it
